language: "perl"

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - g++-4.9

os:
  - linux
#  - osx

#osx_image: xcode7.3

env:
  - ALIEN_INSTALL_TYPE=share DEP_INSTALL_TYPE=share
  - ALIEN_INSTALL_TYPE=share DEP_INSTALL_TYPE=default
  - ALIEN_INSTALL_TYPE=default DEP_INSTALL_TYPE=default
  - ALIEN_INSTALL_TYPE=default DEP_INSTALL_TYPE=share

perl:
  - "5.14"
  - "5.26"

before_install:
  - cpanm ExtUtils::CppGuess

install:
  - ALIEN_INSTALL_TYPE=$DEP_INSTALL_TYPE cpanm --installdeps -n -q .
  - perldoc -l Test::Alien | xargs chmod 644
  - patch -p3 -u -d $( perldoc -l Test::Alien | xargs dirname ) < 0001-effective-linker-flags-ordering.patch
  - perldoc -l Test::Alien | xargs chmod 444

script:
  - perl Makefile.PL && make && make test TEST_VERBOSE=1

after_failure:
  - cat _alien/state.json
